name: firebase_core_dart
description: Pure Dart implementation of FlutterFire core API
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  meta: ^1.15.0

dev_dependencies:
  mockito: ^5.4.4
  test: ^1.25.8

false_secrets:
  - /lib/src/firebase_options.dart
