name: firebase_core_desktop
description: Desktop implementation of firebase_core
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_core_dart:
    path: ../../firebase_core/firebase_core_dart
  firebase_core_platform_interface: ^5.2.1
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  firebase_core: ^3.4.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    implements: firebase_core
    platforms:
      # TODO when doing development on macOS, uncomment this.
      # macos:
      #   dartPluginClass: FirebaseCore
      #   pluginClass: none
      linux:
        dartPluginClass: FirebaseCore
        pluginClass: none
      windows:
        dartPluginClass: FirebaseCore
        pluginClass: none

false_secrets:
  - /example/lib/main.dart
