name: firebase_auth_dart_example
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0

dependencies:
  ansicolor: ^2.0.3
  args: ^2.5.0
  cli_util: ^0.4.1
  firebase_auth_dart: 
    path: ../
  firebase_core_dart: 
    path: ../../../firebase_core/firebase_core_dart
dependency_overrides:
  firebase_auth_dart:
    path: ../
  firebase_core_dart:
    path: ../../../firebase_core/firebase_core_dart
