name: firebase_auth_desktop
description: Windows and Linux implementation of firebase_auth
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  desktop_webview_auth: ^0.0.15
  firebase_auth: ^5.2.1
  firebase_auth_dart:
    path: ../../firebase_auth/firebase_auth_dart
  firebase_auth_platform_interface: ^7.4.5
  firebase_core: ^3.4.1
  firebase_core_dart:
    path: ../../firebase_core/firebase_core_dart
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  async: ^2.11.0
  firebase_core_platform_interface: ^5.2.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    implements: firebase_auth
    platforms:
      # TODO when doing development on macOS, uncomment this.
      # macos:
      #   dartPluginClass: FirebaseAuthDesktop
      #   pluginClass: none
      linux:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none

false_secrets:
  - /example/**
