name: firebase_auth_dart
description: Pure Dart implementation of FlutterFire Auth API
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_core_dart:
    path: ../../firebase_core/firebase_core_dart
  firebaseapis: ^0.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  meta: ^1.15.0
  storagebox: ^0.1.0+2

dev_dependencies:
  async: ^2.11.0
  build_runner: ^2.4.12
  mockito: ^5.4.4
  test: ^1.25.8

false_secrets:
  - /example/bin/firebase_auth_dart_example.dart
  - /test/firebase_auth_dart_test.dart
