name: firebase_functions_dart
description: Pure Dart implementation of FlutterFire CloudFunctions API.
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 0.1.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.18.0
  firebase_auth_dart:
    path: ../../firebase_auth/firebase_auth_dart
  firebase_core_dart:
    path: ../../firebase_core/firebase_core_dart
  http: ^1.2.2
  meta: ^1.15.0
  storagebox: ^0.1.0+3

dev_dependencies:
  test: ^1.25.8

false_secrets:
  - /test/firebase_functions_integration_test.dart
  - /test/firebase_functions_test.dart
