name: firebase_functions_desktop
description: Desktop implementation of cloud_functions
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 0.2.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  cloud_functions: ^5.1.1
  cloud_functions_platform_interface: ^5.5.35
  firebase_core: ^3.4.1
  firebase_core_dart:
    path: ../../firebase_core/firebase_core_dart
  firebase_core_desktop:
    path: ../../firebase_core/firebase_core_desktop
  firebase_functions_dart:
    path: ../../firebase_functions/firebase_functions_dart
  flutter:
    sdk: flutter
  http: ^1.2.2
  meta: ^1.15.0

dev_dependencies:
  firebase_core_platform_interface: ^5.2.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    implements: cloud_functions
    platforms:
      # TODO when doing development on macOS, uncomment this.
      # macos:
      #   dartPluginClass: FirebaseFunctionsDesktop
      #   pluginClass: none
      linux:
        dartPluginClass: FirebaseFunctionsDesktop
        pluginClass: none
      windows:
        dartPluginClass: FirebaseFunctionsDesktop
        pluginClass: none

false_secrets:
  - /example/lib/main.dart
  - /test/firebase_functions_desktop_test.dart
